ai:
  nvidia_key: nv-test-key
  openai_base: https://api.whatai.cc/v1
  openai_key: sk-RieHLXUpKVClw8ieWHPMwLYDLVksDxEB9wfyTlyq8RiCSOy7
  temperature: 0.5
local:
  command_timeout: 120
  target_host: 192.168.1.100
  xray_path: ./xray/
psm:
  debug: true
  draw_graph: false
  exp_iterations: 5
  query_iterations: 3
  scan_iterations: 5
  sys_iterations: 20
test:
  models:
  - gpt-3.5-turbo
  - gpt4omini
  output_path: result
  save_command: true
  save_history: true
  test_path: ./bench/data.jsonl
web:
  debug: false
  host: 0.0.0.0
  port: 5000
